version: '3'

services:
  app:
    build:
      context: ./node
    depends_on:
      - mysqlsrv
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
      MYSQL_DATABASE: "codeducation"
    ports:
      - '3306:3306'
  adminer:
    image: adminer
    ports:
      - '8080:8080'
  nginx:
    build: 
      context: ./nginx
    ports:
      - '4000:80'